### ISSUE TITLE
Model subclass using SingleTableInheritanceTrait returns model indicated by parent's $singleTableSubclasses?

### ISSUE THREAD

**Issue by domhnallw** [Nanigans/single-table-inheritance#10]
Hi folks:

This may or may not be a weird one.
I've got a model (User) which uses Single Table Inheritance to identify six different classes of user. Basically, my parent class looks a bit like this:

```php
namespace MyNamespace\Models;

class User extends Illuminate\Database\Eloquent\Model
{
    use Nanigans\SingleTableInheritance\SingleTableInheritanceTrait;

    protected static $singleTableTypeField = 'user_role';
    protected static $singleTableSubclasses = [
        'MyNamespace\Models\UserRole1',
        'MyNamespace\Models\UserRole2',
        'MyNamespace\Models\UserRole3',
        'MyNamespace\Models\UserRole4',
        'MyNamespace\Models\UserRole5',
        'MyNamespace\Models\UserRole6',
    ];
}
```

Then I have this child class (in the `MyNamespace\API\Models` namespace this time):
```php

namespace MyNamespace\API\Models;

class User extends MyNamespace\Models\User
{
    protected static $singleTableTypeField = 'user_role';
    protected static $singleTableSubclasses = [
        'MyNamespace\Models\API\UserRole1',
        'MyNamespace\Models\API\UserRole2',
        'MyNamespace\Models\API\UserRole3',
        'MyNamespace\Models\API\UserRole4',
        'MyNamespace\Models\API\UserRole5',
        'MyNamespace\Models\API\UserRole6',
    ];
}
```

The problem I'm finding is that when I do a Model::find(...) on the child user class, I get a model as specified by the *parent* class's `$singleTableSubclasses` property.

Am I doing something stupid? The documentation suggests that this should work?

Things that may be helpful:

 1. This worked fine before I had the need to subclass the models.
 2. I'm using Eloquent *outside* of Laravel, booting it using the Capsule Manager.

Any wisdom on this would be appreciated.
Thanks.

**Comment by bostanio** [comment]
My guess is that you haven't set `$singleTableType` correctly in all the subclasses. It needs to be unique for every subclass. For example If `UserRole1` and `API\UserRole1` shared the same value then its likely that you get the behavior you describe. A little hard to tell without more of the details.

**Comment by domhnallw** [comment]
@bostanio : Yep, I do have the same $singleTableType in (for example) `UserRole1` and `API\UserRole1` - I was doing that entirely on purpose. Basically, for each `UserRole<n>` there's an `API\UserRole<n>` which adds some extra bits used when rendering the data in those models to JSON for return as part of this API I'm building. But for all intents and purposes they're the same class, and should refer to the same model. 

What I was hoping for was if I attempt to invoke `MyNamespace\API\Models\User::find(...)`, then I should get a subclass in the `MyNamespace\API\Models\` namespace, and similarly if I invoke `MyNamespace\Models\User::find(...)` that it should return a subclass in the `MyNamespace\Models` namespace. What you're saying suggests that's not feasible, at least the way I'm doing things now, is that right?

**Comment by domhnallw** [comment]
For clarity, I have exactly six subclasses as shown in the example. For each of these subclasses, `MyNamespace\Models\UserRole<n>`  is subclassed as `MyNamespace\API\Models\UserRole<n>`, adding some methods and such but is otherwise the same model...

**Comment by domhnallw** [comment]
Giving up on the idea of subclassing the models, thanks for the help!
