### ISSUE TITLE
Workaround for subclasses not found with Laravel 5.1+

### ISSUE THREAD

**Issue by inthroxify** [Nanigans/single-table-inheritance#11]
Maybe I am crazy, but I couldn't get the overview examples to work on laravel 5.1 until I changed them to the following:
```
class Vehicle extends Model
{
  use SingleTableInheritanceTrait;

  protected $table = "vehicles";

  protected static $singleTableTypeField = 'type';

  protected static $singleTableSubclasses = [Car::class, Truck::class];
}
```
Note the changing of the $singleTableSubclasses array items from strings to the class name resolution scalars. Using the original 'Car' and 'Truck' strings, I was receiving "Class not found" errors when instantiating those particular classes, but using the class name resolution scalar resolves it for me for some reason. Perhaps it is because I had them in a separate models directory, I am not sure.

Also, it seems that there is no Eloquent class to extend in 5.1, but there is a Model class.

**Comment by bradbird1990** [comment]
@inthroxify I also had this same issue until I found your post in the issues list... I don't think the code requires a change but updating the documentation to match what you wrote will suffice. Looks like the project hasn't been worked on in a while anyway.
