### ISSUE TITLE
Laravel 5.2.*

### ISSUE THREAD

**Issue by eightyfive** [Nanigans/single-table-inheritance#16]
Hi,

```
composer require "nanigans/single-table-inheritance:0.5.*"
```
Doesn't work:
```
Your requirements could not be resolved to an installable set of packages.
```

This is because the lastest version on Packagist is 0.5.0 only "supports" Laravel 5.1.*:
https://packagist.org/packages/nanigans/single-table-inheritance

I see that you updated `dev-master` to Laravel 5.2.*:
https://github.com/Nanigans/single-table-inheritance/blob/master/composer.json#L14

Could you publish a new version (0.5.1) on Packagist with new composer.json & Laravel 5.2.* support?

Thanks.

**Comment by eightyfive** [comment]
Work around (tmp):
```
composer require "nanigans/single-table-inheritance:dev-master"
```
Which is obviously not ideal.

**Comment by mtvs** [comment]
@eightyfive I had the same problem, thanks to your information I managed to install it through github.

I added `repositories` attribute to my `composer.json` with the following specification:

    "repositories":
    [
      {
        "type": "package",
        "package": {
          "name": "nanigans/single-table-inheritance",
          "version": "0.5.0",
          "source": {
            "url": "https://github.com/Nanigans/single-table-inheritance.git",
            "type": "git",
            "reference": "master"
          },
          "autoload": {
            "psr-4": {
              "Nanigans\\SingleTableInheritance\\": "src/"
            }
          }
        }
      }
    ]

**Comment by pdiddy** [comment]
Or in your `composer.json` file use `"nanigans/single-table-inheritance": "dev-master"`

**Comment by eightyfive** [comment]
@pdiddy Thx. But can only act as a temporary workaround. `dev-master` is not stable nor recommended for Production.

I leave the issue open as I believe this is still not updated on Packagist.

**Comment by bostanio** [comment]
created a 0.6 version. Let me know if that fixes the problem and we can close this out.

**Comment by pdiddy** [comment]
Works for me -- thanks very much
