### ISSUE TITLE
Abstract base types

### ISSUE THREAD

**Issue by oldtimeguitarguy** [Nanigans/single-table-inheritance#18]
Does this work with abstract base types? I've had issues overriding FromBuilder with abstract base types.

**Comment by a-komarev** [comment]
As I understand it doesn't support abstract base type at this moment.

**Comment by oldtimeguitarguy** [comment]
@a-komarev I'm not sure if this will help you, but after posting this message last year, I ended up writing a simplistic version myself. It's not fancy, but it worked for what I needed.  https://github.com/oldtimeguitarguy/eloquent-single-table-inheritance

**Comment by a-komarev** [comment]
Thanks for sharing your work @oldtimeguitarguy, but it doesn't work with abstract base class too :(

**Comment by bostanio** [comment]
@oldtimeguitarguy I'm as confused as @a-komarev as to how this is different :)

What is broken with abstract base classes? It's not an area I've explored much but it doesn't sound like it would be a terribly hard problem to fix. Do you have stack traces or failing test cases that you can attach so we can track this down?

**Comment by oldtimeguitarguy** [comment]
@bostanio

It’s not really that different. I was just throwing an alternative into the mix. I was pretty adamant about having an abstract base class at first, but Eloquent don’t play that game. ;-)

In the end, I found the concrete base class to be more powerful anyway. You can make a request on behalf of the base class and it will return a collection of child classes, matched by their db definition.

**Comment by a-komarev** [comment]
@bostanio you cannot instantiate abstract class. So if Base class is abstract there is no way to pass it to relation.
I think the only way to deal with it - provide factory class to relation which will decide which subclass should be instantiated.

**Comment by bostanio** [comment]
I'd like to be able to support it but its very painful given the Illuminate internals. The trade off isn't particularly worth it for the relatively simple cost of having non abstract classes
