### ISSUE TITLE
Loading from relationship fails due to unknown type

### ISSUE THREAD

**Issue by alexwhitman** [Nanigans/single-table-inheritance#20]
Using the following code as an example:

``` php
class Zoo extends Model
{
    public function animals()
    {
        return $this->hasMany(Animal::class);
    }

}

class Animal
{
    use SingleTableInheritanceTrait;

    protected $table = 'animals';

    protected static $singleTableTypeField = 'type';

    protected static $singleTableSubClasses = [ Elephant::class ];

    public function zoo()
    {
        return $this->belongsTo(Zoo::class);
    }
}

class Elephant extends Animal
{
    protected static $singleTableType = 'elephant';
}
```

Assuming a Zoo has been saved with some animals associated, calling `Zoo::with('animals')->get();` fails with `Nanigans\SingleTableInheritance\Exceptions\SingleTableInheritanceException with message 'Cannot construct newFromBuilder for unrecognized type=elephant'`.

This is because `get_called_class` at https://github.com/Nanigans/single-table-inheritance/blob/master/src/SingleTableInheritanceTrait.php#L46 returns the base `Animal` class which doesn't know about the `elephant` type.

A better solution for this would be to define the type in the sub-class map:

``` php
    protected static $singleTableSubClasses = [ 'elephant' => Elephant::class ];
```

**Comment by bostanio** [comment]
pull request with test cases would be easily accepted.

**Comment by mikmanic** [comment]
I solved it using relations morph map 
```
Relation::morphMap(Animal::singleTableSubClassMap());
```
Run it on AppServiceProvider boot, for example.

**Comment by patricknazar** [comment]
I had this issue to, you have a typo. `$singleTableSubClasses ` should be `$singleTableSubclasses `. However, it wasn't the end of my troubles.

**Comment by bostanio** [comment]
Failing test case in a PR would help us track down any issues.

**Comment by bostanio** [comment]
This seems like a configuration error.
