### ISSUE TITLE
Numeric type values fail

### ISSUE THREAD

**Issue by mikmanic** [Nanigans/single-table-inheritance#22]
Wrong classes gets instantiated when using numeric type values and calling Parent::all().
This is because getSingleTableTypeMap() uses merge_array to cache parent class types (see. SingleTableInheritanceTrait line 65).
This also caused inverted relation to fail. I'd suggest using:

```
$typeMap += $subclass::getSingleTableTypeMap());
```

**Comment by bostanio** [comment]
Pull request with test cases gratefully accepted.

**Comment by mrvanwagoner** [comment]
Did you try enclosing the number in quotes? eg. protected static $singleTableType = '1'

**Comment by bostanio** [comment]
This is fixed in 0.8.4
