### ISSUE TITLE
Laravel 5.3 compatibility

### ISSUE THREAD

**Issue by isaackearl** [Nanigans/single-table-inheritance#23]
Laravel 5.3 is close to being released.  I'm hoping this package will be updated to work with it.

**Comment by shabushabu** [comment]
Any news on 5.3 compatibility now that it's out?

**Comment by isaackearl** [comment]
@shabushabu If you are looking for a temporary solution I found that this other person's fork is working in 5.3 and you can use it until this one gets updated.

https://github.com/cfothergill/single-table-inheritance

**Comment by bostanio** [comment]
fixed a while ago
