### ISSUE TITLE
Change type attribute to convert a model to another

### ISSUE THREAD

**Issue by sylvainma** [Nanigans/single-table-inheritance#30]
I'm trying to change the column 'type' that stores le class name. I use:
```
$instance = Model::find($id);
$instance->type = 'other'; // 'other' stands for Other model which shares the same table
$instance->save();
```

But when saving, type hasn't change. How should we do that with Nanigans/single-table-inheritance ? Actually is it possible to convert a row in the table changing his type column directly ? Thanks!

**Comment by bostanio** [comment]
That isn't really how the plugin works. The type column is infer from the Class of the Model object. What is the use case for trying to change it like this?

**Comment by sylvainma** [comment]
I have one table `users` et I use Nanigans/single-table-inheritance on it to host two models: `Users` and `Members`. I have the column `type` to set which class a row belongs to (`user` or `member`).

I want to convert some rows from model User to Member (when they get rights on my application). So, I was thinking about changing the `type` column directly for that, from `user` to `member`.

So you think I am using Nanigans/single-table-inheritance in a wrong way?

**Comment by bostanio** [comment]
If you have a User that you want to turn into a Member I think you'd want to create and Member model from the User model with the same properties and importantly the same id and then save that back.

**Comment by kentdahl** [comment]
Since I ran into the same kind of issue, I'd just like to note that I ended up using the global update functionality of Eloquent instead. Something like:

```
Model::where('id', '=', $id)->update(['type' => 'other']);
```

This seems to work well so far.

**Comment by wtfz** [comment]
I would like to add a workaround for others who have the same issue. You can use `saveQuietly()` to save the model without dispatching any event (skip `saving` method in the package observer). However, you need to manually re-update the updated_at (or other column other than single table column) using new instance to dispatch the `saving` event back for other observer.

```
$instance = Model::find($id);
$instance->type = '\Other\Type\Class';
$instance->saveQuietly();

$newInstance = Model::find($id);
$newInstance->update['updated_at' => now()];  // manually update to trigger other observer
```

In my use case, I used the subclass for historical record in my approval process. When new record type approved, it will switched to current type and previous current type will switched to historical type.
