### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by umairyounus** [Nanigans/single-table-inheritance#32]
Laravel 5.4 is ready to go live next week. Can you please add a support for it?

**Comment by bostanio** [comment]
Pull request would be gladly accepted.

**Comment by adamthehutt** [comment]
At the risk of pointing out the obvious, a [pull request was submitted for this](https://github.com/Nanigans/single-table-inheritance/pull/33). 

+1 on the need for 5.4 compatability

**Comment by stefanthorpe** [comment]
+1 from me also

**Comment by kklon** [comment]
+1

**Comment by bostanio** [comment]
v 0.7.1 release with 5.4 support.
