### ISSUE TITLE
Event observers (created, deleting, etc) on the parent class don't get triggered for subclasses.

### ISSUE THREAD

**Issue by toddnestor** [Nanigans/single-table-inheritance#34]
I added an Observer for my User class but it doesn't get triggered when my SuperAdmin (which is a subclass of User) gets created/deleted, etc.

**Comment by bostanio** [comment]
Can you provide a failing test case or better a PR?

**Comment by craigbartholomew** [comment]
When observing the 'retrieved' event from my subclass, the event handler never gets called.

**Comment by craigbartholomew** [comment]
In Eloquent's base `Model` class, the following line is called from the `newFromBuilder` method

`$model->fireModelEvent('retrieved', false);`

However, in the overridden method in `SingleTableInheritanceTrair`, the same event is never fired.

**Comment by bostanio** [comment]
Pull request happily considered. Sounds like it would be an easy fix.

**Comment by bostanio** [comment]
The original issue of created etc events is just how Eloquent works. You need to observe the events on subclasses individually. Nothing is different wit STI. The `retrieved` event is a real bug tracked separately as #58.

**Comment by tractorcow** [comment]
I solved with with a custom observe method on STI models.


```php
    public static function observe($classes): void
    {
        parent::observe($classes);

        // Note: Must apply to each subclass for STI classes
        foreach (static::getSingleTableTypeMap() as $typeClass) {
            /** @var static $typeClass */
            if (is_subclass_of($typeClass, static::class)) {
                $typeClass::observe($classes);
            }
        }
    }
```
