### ISSUE TITLE
Using pluck() on Query Leads to Crash

### ISSUE THREAD

**Issue by common-link-dev** [Nanigans/single-table-inheritance#35]
Hi,

first I want to thank you for this great package, it helps us a lot in several cases within our projects.

After upgrading Laravel to version 5.3 we found a bug. When using pluck() with Eloquent queries where the Eloquent class using STI, the application crashes with following message:

> Nanigans\SingleTableInheritance\Exceptions\SingleTableInheritanceException with message 'Cannot construct newFromBuilder without a value for type'

Example:
Lets say we have a class EloquentModel that applies and configures STI, the type field is named 'type'. There is a class MyEloquentModel that inherits the EloquentModel class and configures the type. Now I want to get all IDs from MyEloquentModel, I use following code:

`MyEloquentModel::pluck('id');`

This leads to the error from above. Do you have an idea how to fix this problem?

Many thanks and best wishes
David

**Comment by bostanio** [comment]
A failing test case in a pull request would be helpful to track this down.

**Comment by 00madz** [comment]
I ran into a similar issue when combining with the sluggable library trait. I ended up changing line 191:

`throw new SingleTableInheritanceException("Cannot construct newFromBuilder without a value for $typeField");`

To be:

`return parent::newFromBuilder($attributes);`

I guess on the assumption if you are dealing with a subset of fields you are probably not using full objects and base functionality is fine? I'm sure of the implications of doing this though, there are probably consequences

**Comment by grzegorz-rozycki** [comment]
Same issue here. Instead of modifying the package I've overridden the `newFormBuilder` method.
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Nanigans\SingleTableInheritance\Exceptions\SingleTableInheritanceException;
use Nanigans\SingleTableInheritance\SingleTableInheritanceTrait;

class MyEloquentModel extends Model
{
    use SingleTableInheritanceTrait {
        newFromBuilder as private traitNewFromBuilder;
    }
    
    // ...

    public function newFromBuilder($attributes = array(), $connection = null) {
        try {
            return $this->traitNewFromBuilder($attributes, $connection);
        } catch (SingleTableInheritanceException $e) {
            return parent::newFromBuilder($attributes, $connection);
        }
    }
}
```

**Comment by nilay** [comment]
I stuck with same issue and hoping next release will have the fix.

**Comment by bostanio** [comment]
Fixed.
