### ISSUE TITLE
Configurable $singleTableSubclasses

### ISSUE THREAD

**Issue by pkid169** [Nanigans/single-table-inheritance#38]
Hi,

I wanna make `$singleTableSubclasses` configurable (i.e. store this under config and read it as something like `$singleTableSubclasses = config('vehicle.subclasses');`. Right now it's a static variable so this is not possible. Is there a quick way to achieve this without rewriting too much of your implementation?

Cheers

**Comment by bostanio** [comment]
What's the use case for making it externally configurable?

**Comment by pkid169** [comment]
**Use case**
We're writing an SDK. Sticking with the vehicle example - we, the SDK team, provides the base class `Vehicle`. Developers who use our SDK can extend Vehicle with their own implementation.

**Rationale**
I don't want the developers to touch the `Vehicle` class (which is where `static $singleTableSubclasses` is defined currently). Instead it'll be great to read that externally via some config file, which I don't mind the developer to edit (in fact, I'll provide some tooling to automate that - e.g. think `php artisan make:vehicle`).

**Comment by bostanio** [comment]
This seems really hard to support in a non-invasive way. Its a pretty unique use case that you wouldn't have control over all the classes your storing in a single table. Closing for now. If you can provide a PR with a small footprint I'd be happy to take a look.
