### ISSUE TITLE
belongsToMany relation doesn't load

### ISSUE THREAD

**Issue by ilvalerione** [Nanigans/single-table-inheritance#41]
Hello,
I met a strange behavior applying SingleTableInheritanceTrait on a model used in a BelongsToMany relation:

Single table inheritance structure:
```php
class Animal extends Model {
    use SingleTableInheritanceTrait;
}

class Elephant extends Animal { }
```

Many to Many relation with "single table inherited" model:
```php
class Zoo extends Model { 

    public function animals(){
        return $this->belongsToMany(Animal::class, 'animal_zoo', 'zoo_id', 'animal_id');
    }

}
```

The relation load only when I explicitly "touch" the relation property:
```php
return $zoo->animals;
```

It doesn't load using "with" or "load" eloquent methods:
```php
// Create relations
Zoo::find(1)->animals()->attach([1, 2, 3]);

// Using "with"
return Zoo::with('animals')->get();

// Using "load" in booted model 
$zoo = Zoo::find(1);
return $zoo->load('animals');

/*
 * In both case the result is
 */
{
  name: 'Super funny Zoo',
  address: '...',
  animals: [] // <-- empty array for belonsToMany relation using SingleTableInheritanceTrait 
}
```

This example represents a return value for an api call by javascript frontend. It's an easy reproducible issue. 

Can I use some tricks to load `belongsToMany` relation properly?

**Comment by patricknazar** [comment]
I'm also facing this issue.

**Comment by patricknazar** [comment]
It has something to do with the pivot object not setting, and not matching up eager loaded results, I believe.

**Comment by patricknazar** [comment]
Ok, my workaround is to add `'pivot_zoo_id'` and `'pivot_animal_id'` to the `protected $persisted` array

**Comment by bostanio** [comment]
fixed
