### ISSUE TITLE
"Field 'type' doesn't have a default value" when saving a model

### ISSUE THREAD

**Issue by AnixPasBesoin** [Nanigans/single-table-inheritance#43]
# First: Making sure I'm using the right package

I'm only using the Eloquent ORM (not the whole Laravel framework), and for some reason, I couldn't get your demo work on my project.
Before posting any of my failing code (nothing fancy, just a simple test), I want to know if this package supports the independent Eloquent ORM provided in [illuminate/database](https://packagist.org/packages/illuminate/database).
So, is this package meant to be used with the whole Laravel framework or I might have missed something in my demo?

# Second: Now, here's my attempt
```
use Nanigans\SingleTableInheritance\SingleTableInheritanceTrait;

class A extends Model
{
    use SingleTableInheritanceTrait;
    protected $table = "a";
    protected static $singleTableTypeField = 'type';
    protected static $singleTableSubclasses = [B::class];
}
class B extends A
{
    protected static $singleTableType = 'b';
}
// In some other file
$b = new B(); // some inits as well
$b->save(); // This line is throwing an exception
```
I'm getting this error: 

> Field 'type' doesn't have a default value

**Comment by AnixPasBesoin** [comment]
My workaround was to overload the default constructor of the child classes and make sure the appropriate type is set at construct time.
I'm not sure this if this is not breaking somewhere else since I haven't tested it in advanced scenarios.
Use it with that in mind.

**Comment by aiakane16** [comment]
i have used this with the [illuminate/database](https://packagist.org/packages/illuminate/database) with no problem

**Comment by bostanio** [comment]
This seems to be a completely vanilla use case that there are lots of unit tests around that prove it works and only rely on Illuminate. Without a failing test case its hard to reproduce.
