### ISSUE TITLE
One record two types.

### ISSUE THREAD

**Issue by CristianH033** [Nanigans/single-table-inheritance#46]
Is there a way to make a record belong to two types of model at the same time?

**Comment by mazyvan** [comment]
Supuse the `Vehicle` super Model has `Bike` and `Car` extending from it. So the type in the column would be `car` and `bike` for example. But what I think @CristianH033 means is that can `car` and `bike` could be set together. I do not know if I explain myself very well.

I thought the same thing. But I realized I could use the [Multi Level Class Hierarchies](https://github.com/Nanigans/single-table-inheritance/#multi-level-class-hierarchies)
 to do that. just defining a class that group that two clases and extending like for example `car` and `bike` from it.

**Comment by bostanio** [comment]
Closing out a long ago asked question. Either this is just supported with multi level class hierachies or the request is for multiple inheritance with isn't practical to support. With more details we could revisit.
