### ISSUE TITLE
Can't create a new record directly form the base class

### ISSUE THREAD

**Issue by mazyvan** [Nanigans/single-table-inheritance#50]
I need to be able to create a record directly from the base class because of the code base that I have. 

Obviously I can't refactor everything with out a step by step process. And also I need to support a type field without a `class`, like 'other' for instance. I know this issue/proposal was also asked here: #47 and I know the trade offs this could imply. We love this trait but as I've already said, having a large base code we need some way to add functionality in small cycles. I'm not the only one in this situation.

Right now we have a workaround idea. For those how have the same problem.
A `Base Class` that `extends` from `Model` in which we have all of our configuration then the normal `class` `extends` from it and then the inheritances. So we can call the `base` anywhere without problems.

```php
class VehicleBase extends Model
{
    protected $table = "vehicles";

    // Conventional Model configuration goes here
}

```
```php
use Nanigans\SingleTableInheritance\SingleTableInheritanceTrait;

class Vehicle extends VehicleBase
{
    use SingleTableInheritanceTrait;

    protected static $singleTableTypeField = 'type';
    protected static $singleTableSubclasses = [Car::class, Truck::class];
}

```
```php
class Car extends Vehicle
{
    protected static $singleTableType = 'car';
}

```
```php
class Truck extends Vehicle
{
    protected static $singleTableType = 'truck';
}
```

   
Anyway, This is a great tool. Thanks for the work

**Comment by mazyvan** [comment]
#47

**Comment by bostanio** [comment]
Can you illustrate what it is that you really need? What is it that requires:

> I need to be able to create a record directly from the base class because of the code base that I have.

I general these use cases are a code smell of some other factoring problem. As stated in #47 there are numerous edge cases that quickly evolve from this kind of approach that are normally solved better in you application logic than they are in this trait.

**Comment by bostanio** [comment]
Closing out a long ago asked question. With more details and a PR we can revisit.

**Comment by darron1217** [comment]
@jonspalmer 
I need the same functionality in my project.
What is best-practice for creating Model from form request?

**Comment by jonspalmer** [comment]
@darron1217 Can you elaborate on the need. Some example code would be helpful to be able to offer advice on the right solution.

**Comment by darron1217** [comment]
@jonspalmer 
As I said, Form Request situation need it.

Imagine that you are registering vehicle with type option.

HTML
```html
<form>
    <select name="type">
        <option>car</option>
        <option>truck</option>
    </select>
    <input type="text" name="color" />
</form>
```

PHP
```php
public function store(Request $request)
{
    Vehicle::create($request);
}
```

**Comment by jonspalmer** [comment]
As mentioned in #47 the trick is you really need to create an instance of the concrete class. Perhaps you can use the type map to do that it would be something like

```php
$childTypes = Vehicle::getSingleTableTypeMap();
$requestType = $request['type'];
$requestTypeClass = $childTypes[$requestType];
(new $requestTypeClass)->newInstance([], true);
...
```

**Comment by darron1217** [comment]
@jonspalmer 
That's exactly what I'm doing.

Then, how about adding it as function like `Vehicle::createType()` and `Vehicle::createManyTypes()` ?
cuz it's really common situation when using this package.

**Comment by jonspalmer** [comment]
What would the API be on those methods? Can you Pseudo code it? A PR with tests would be welcomed.

**Comment by darron1217** [comment]
Okay, I'll create PR for it.

BTW, will you re-open this issue?

**Comment by darron1217** [comment]
@jonspalmer I created PR. Please check
