### ISSUE TITLE
Broken link in README - Mark Smith's website is gone

### ISSUE THREAD

**Issue by JFossey** [Nanigans/single-table-inheritance#51]
I needed to explain STI to some colleagues to find the link that is referenced in the README to "Mark Smith's" blog no-longer exists.

So I had to resort to using Internet Archive Wayback Machine:

https://web.archive.org/web/20171224233536/http://www.colorfultyping.com/single-table-inheritance-in-laravel-4/

**Comment by bostanio** [comment]
Fixed. Thanks for the heads up.
