### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by DenzoNL** [Nanigans/single-table-inheritance#52]
As the title says, it would be very nice to have Laravel 5.7 support as it has been tagged today. From what I've seen in the upgrade guide, not too much has changed, so perhaps it's nothing more than a `composer.json` update.

edit: Added a PR: #53

**Comment by abiturma** [comment]
+1

**Comment by DenzoNL** [comment]
@bostanio Could you please take a look at this? :+1:

Thanks in advance!

**Comment by tonimitrevski** [comment]
+1

**Comment by Red-AB** [comment]
Hi, any news this issue ?

**Comment by Red-AB** [comment]
Any news about this issue ?

**Comment by DenzoNL** [comment]
Haven't heard anything from the author yet, it seems he or she isn't active on GitHub anymore. I'm tempted to fork it and patch it myself, but I'm not really willing to maintain this package, I guess.

**Comment by Red-AB** [comment]
Then I guess that it is probably time to move forward with another single table inheritance package, this one is not maintained anymore for a little while anyway. Thanks for your help @DenzoNL !
