### ISSUE TITLE
Cannot insert record

### ISSUE THREAD

**Issue by andyyapwl** [Nanigans/single-table-inheritance#59]
Hi, 

I noticed there is no record inserted into database..but if I changed the below:
$instance = (new $class)->newInstance([], true);
to 
$instance = (new $class)->newInstance();

it works. However, the changes will pose the update problem for duplicate entry in database.

Any help will be much appreciated:) Thanks

**Comment by bostanio** [comment]
You've jumped to a solution before describing the problem. Can you provide the code that does t work or better yet a failing test?

**Comment by andyyapwl** [comment]
Code example:
$user->cars()->saveMany($cars);

Invoking saveMany function does not save new cars into database. If I remove SingleTableInheritanceTrait, it's able to save. 

Btw, thanks for this great library!

**Comment by bostanio** [comment]
I added a test around saveMany looks like it works fine. There must be something else going on with your actually use case but its pretty hard to know what the difference is. I wonder if something is going wrong with validation or db constraints. 

Closing for now. If you can provided a failing test case in a PR I'd be happy to look more.

**Comment by andyyapwl** [comment]
It occurred when hydrate function was called i.e.
$cars = Car::hydrate( $data["cars"] );
$user->cars()->saveMany($cars); //Data not inserted into database when objects are instantiated by hydrate function

So I replaced it with a manual approach:
$className = 'App\\'  . 	$type;
$car = new $className($car_array);
array_push($cars, $car);

**Comment by bostanio** [comment]
The Scope isn't involved in the saving of the objects in saveMany() except that it manipulates the `type` attribute to set it according to the class that is being instantiated. I would imagine in your example that your `hydrate` call results in N `Car` objects being inserted into the database. Whatever the `$data` array has for type will get ignored. This is exactly the desired behavior. To properly create the right objects you must instantiate the appropriate classes directly. It really has to work this way, imagine that the subclasses of `Car` have getters, setters and other mutators of the attributes. Those won't get called if you hydrate `Car` objects either.

**Comment by andyyapwl** [comment]
thanks for the detailed explanation!
