### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by thomasschiet** [Nanigans/single-table-inheritance#62]
This package doesn't work for Laravel 6.0 because it uses the `starts_with` helper, which has been [removed](https://laravel.com/docs/6.0/upgrade#helpers) from the framework.

**Comment by SeoRoman** [comment]
is this going to be merged in? Starting a new project with L6 and would like to see this functionality. I agree with others that adding the laravel/helpers dependency should be unnecessary as the package should update with this PR
