### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by luoshiben** [Nanigans/single-table-inheritance#7]
Hi there! Great package. Any plans to update for L5? Thanks!

**Comment by bostanio** [comment]
We've a little bit left Laravel behind and don't have  lot of resources to devote to it. Pull requests would be happily accepted.

**Comment by pdiddy** [comment]
You might be interested in fork phaza/single-table-inheritance

**Comment by newtonianb** [comment]
L5 Support :+1:

**Comment by bostanio** [comment]
Laravel 5 support as of version 0.5.*
