### ISSUE TITLE
Double persistence

### ISSUE THREAD

**Issue by petermein** [Nanigans/single-table-inheritance#8]
I'm stuck in a scenario where im using Mutators an Accessors in my model. This works fine up until i want to create a model. Because the attributes are set twice. Let me explain. 

These are my accessors and mutators. You have to give somekind of enumeration class on those fields. And the mutator tranforms it into a string.  
```php
        /**
         * @param $value
         * @return AccessorType
         */
        public function getAccessorTypeAttribute($value)
        {
            return new AccessorType($value);
        }

        /**
         * @param AccessorType $accessorType
         */
        public function setAccessorTypeAttribute(AccessorType $accessorType)
        {
            $this->attributes['accessor_type'] = $accessorType->getValue();
        }
```

This goes fine the first time and the internal attributes table is set with the string. 
But after the saved event is catched by the Observer. 

The model tries to fill itself a second time but now with the data from the attributes table without using the mutators first. 

Problem is internally AccessorType is a string but when used you or set you need it wrapped in the enumeration class. So PHP throws an error because the typehinting fails.

__The first setAttribute is called in the__
Model->fill() function

__The second after__ 
setSingleTableInheritanceType();
and then it calls the magic method __set()

![screenshot 2015-07-23 13 38 47](https://cloud.githubusercontent.com/assets/311652/8849470/33907afa-3140-11e5-86bc-d99f4368d9cf.png)

**Comment by bostanio** [comment]
I'm not 100% clear on the problem but it does strike me as strange that your getter takes a parameter. Thats not have Eloquent expects get/set methods to work and perhaps something is going wrong there.

**Comment by petermein** [comment]
Both mutators and accessor need a parameter. 
http://laravel.com/docs/4.2/eloquent#accessors-and-mutators

**Comment by bostanio** [comment]
A failing unit test as part of a pull request (ideally with a fix) would help track this down.

**Comment by petermein** [comment]
I almost tracked the issue, il keep you posted

**Comment by petermein** [comment]
See PR #9
